### ISSUE TITLE
Concurrent reads cause incorrect image data

### ISSUE THREAD

**Issue by zekenie** [leetreveil/musicmetadata#100]
Hello,

We were traversing a directory and extracting metadata from each mp3 or m4a. It worked great, but the album art often came back incorrectly (songs were associated with incorrect art). *We worked out a fix for the issue on our end*. We first tried to read the files in series. That didn't work. Then while reading in series we copied the image buffer onto a new property on the metadata object. This copied buffer had the correct data. We hypothesize that your `metadata -> picture -> data` buffers are actually references to one buffer? We think that by running it over and over again, we're rewriting the data in that buffer.

**Comment by leetreveil** [comment]
Hi,

Is there some reproducible test case we could develop with the existing sample mp3 files?

I think i've seen something similiar to this with the ogg parser: https://github.com/leetreveil/musicmetadata/blob/a703492013903fdcc12b41128f68459d151eda4b/lib/ogg.js#L58

**Comment by zekenie** [comment]
Here's our fix

```js
var Promise = require('bluebird')
var fs = require('fs')
var mm = require('musicmetadata')


module.exports = function(name) {
  return new Promise(function(resolve, reject) {
    mm(fs.createReadStream(name), function(err, metadata) {
      if(err) return reject(err)
      metadata.path = name

      metadata.picture = metadata.picture[0] || { data: new Buffer(0), format: 'jpg' }
      var x = new Buffer(metadata.picture.data.length)
      metadata.picture.data = metadata.picture.data.copy(x)
      metadata.picture.data = x

      resolve(metadata)
    })
  })
}
```

I think if you just remove our buffer modification and then do 

```js
var metaWrapper = require('./metaWrapper')
Promise.map([/*array of file paths*/, function(song) { return metaWrapper(song) }).then(console.log).catch(console.error)

you should get the issue we found

**Comment by leetreveil** [comment]
Published a new version, give it a whirl!

**Comment by zekenie** [comment]
Thanks!! :+1:
