### ISSUE TITLE
No metadata no error when reading this file

### ISSUE THREAD

**Issue by randyccm** [leetreveil/musicmetadata#101]
Trying to process a batch of songs, but when I hit this particular mp4 file, the application just hangs or fails silently. Tried stepping through and debugging, but its not coming back with anything. Tried throwing error on error and tried checking for no metadata, and still nothing.

Any idea why?

**Comment by leetreveil** [comment]
Can you send me the sample mp4 file?

**Comment by randyccm** [comment]
[01 - Baby Come Home.mp4 | uploaded via ZenHub](https://files.zenhub.io/561d61e14e5de1c63afe7d3d)

**Comment by leetreveil** [comment]
there's no metadata in this file, the question is should the library throw an error on no metadata found or should it fail silently.

I'm not seeing the code hanging on the file.

**Comment by randyccm** [comment]
Right it would be nice to get an error back. But I guess its just failing silently now. So then how do I know how to check for a silent error? `!metatdata` doesn't work since the callback never gets invoked. Thanks!

```javascript
var stream = fs.createReadStream(configs.shared + file);

mm(stream, {duration: true}, function(error, metadata) {
    if (error) {
      console.log('Error getting metadata for file: ' + file);
      return callback(error);
    }

    return callback(file, metadata);
});
```
