### ISSUE TITLE
ID3v2.3 TPE1

### ISSUE THREAD

**Issue by egoroof** [leetreveil/musicmetadata#105]
Hello!

After setting two artists via Windows Explorer and reading it via musicmetadata I've got an array with single element containing both artists seperated with character "/" like ['artist one/artist two']. But it should contain an array with two elements like ['artist one', 'artist two'], right?
UPD (08.12.15): The same problem with genre (TCON).

Also shouldn't albumartist (TPE2) be a string. In the spec (http://id3.org/id3v2.3.0) there is nothing about separator (like in TPE1).

Thanks!

**Comment by leetreveil** [comment]
We don't split artists by `/`, see https://github.com/leetreveil/musicmetadata/issues/67 for rationale.

You can split this yourself if you need that behaviour.

**Comment by egoroof** [comment]
Anyway thaks for the lib, I use it to test my browser ID3 writer.
