### ISSUE TITLE
AssertionError: number too large

### ISSUE THREAD

**Issue by vankasteelj** [leetreveil/musicmetadata#107]
Hi,

I use musicmetada as a dep to 'media-library', you can read my initial BR: https://github.com/guillaume86/media-library/issues/2

>When I test on a small folder with 8 songs, it works perfectly.
>
>When trying my entire library, I have this:
>
>>Uncaught AssertionError: number too large
- at `media-library\node_modules\musicmetadata\node_modules\int53\index.js:53:3`
- coming from `media-library\node_modules\musicmetadata\node_modules\through\index.js:14:43`

Thanks

**Comment by leetreveil** [comment]
Can you find and post the file that is causing the error?

**Comment by vankasteelj** [comment]
Here's one of the faulty:
[f.zip](https://github.com/leetreveil/musicmetadata/files/77176/f.zip)

**Comment by leetreveil** [comment]
Which version of `musicmetadata` are you using? I've tested using the latest version and it's working ok:

```
{ title: 'the holy econnomic war',
  artist: [ 'noir desir' ],
  albumartist: [ 'noir desir' ],
  album: 'dies irae 2',
  year: '1994',
  track: { no: 2, of: 0 },
  genre: [ 'rock francais' ],
  disk: { no: 0, of: 0 },
  picture: [],
  duration: 306.932 }
```

**Comment by vankasteelj** [comment]
erf those people not updating their deps... it's 0.x.x, which resolves in 0.4.6 x) Let me try to update (hoping you didn't break the world in 2 major updates). Anyway I'm gonna report back to media-library

**Comment by vankasteelj** [comment]
Ok, I forced update but it still can't read it: `Cannot read property 'hasOwnProperty' of undefined` at `musicmetadata\lib\index.js:66`

**Comment by vankasteelj** [comment]
You might want to throw something like: 

    if (typeof opts === 'function') {
      callback = opts
      opts = {}
    }
    if (!opts) throw 'callback is mandatory'

Or take care of this otherwise, maybe `if (!opts) opts = {}`, i'm unsure what those do anyway.

**Comment by leetreveil** [comment]
Looks like you want to update the usage of `musicmetadata` in `media-library`.

**Comment by vankasteelj** [comment]
yes but i'm pointing out that you have an unhandled error there
