### ISSUE TITLE
fails to work properly in the browser

### ISSUE THREAD

**Issue by dryajov** [leetreveil/musicmetadata#109]
I'm trying to use this in the browser however, I cant get it to work properly. I'm getting mangled or partial track titles and other information. I believe that the issue has something to do with encoding - UTF-16 vs UTF-8, I'm not sure tho. 

Here is the relevant code:

```
    return Promise.resolve($.ajax({
            url: track.location,
            withCredentials: true,
            cors: true,
            responseType: 'arraybuffer'
        })
    ).then(function (result) {
            return new Promise(function (resolve, reject) {
                MM(new Blob([result]), function (err, result) {
                    if (err) {
                        return reject(err);
                    }
                    console.log(result);
                    resolve(result);
                });
            });
        }).catch(function (error) {
            console.error(error);
            return resolve(track);
        });
```

Running a similar snippet, with the same exact track works in node, but fails in the browser. Using the original id3-node implementation also works, but fails to read the image data correctly.

**Comment by leetreveil** [comment]
Interesting, can you send me the file?
