### ISSUE TITLE
Npm Install failure on fresh clone

### ISSUE THREAD

**Issue by xhocquet** [leetreveil/musicmetadata#111]
`prova` package was part of the big npm unpublish fiasco:
https://www.npmjs.com/package/prova

Two options: 
Have the last version put back up on the repo, since it currently has nothing.
OR
Find another library that does the same thing.

**Comment by xhocquet** [comment]
I have just messaged npm support asking for them to publish the last available version, if possible. I'll update with a response.

**Comment by leetreveil** [comment]
let's wait for npm to publish the last available version :+1:

**Comment by xhocquet** [comment]
`prova` package has been restored, now `package-path`

**Comment by rodu** [comment]
I have some problems on running `npm test`. Error: Cannot find module 'ansi-codes'

The `prova` package may have been restored, but there are some of its dependencies that seem to be still missing from npm. The `style-format` package is used by prova but it's missing: https://www.npmjs.com/package/style-format

And the `ansi-codes` of course which gives the error I get above:
https://www.npmjs.com/package/ansi-codes

Hope this helps too.

**Comment by xhocquet** [comment]
Yeah, it's just going to keep chaining until all the packages are
republished. The problem is that azer made all his dependencies `"*" `, so
when the security packages became the most recent they all broke. The old
versions are still there and installable, but there's just too many
interdependencies and the packages belong to a bunch of people now.

**Comment by leetreveil** [comment]
I've replaced `prova` with `tape` in: https://github.com/leetreveil/musicmetadata/commit/f2152d94ad5cd5e043a18a11a70a53836979c9ee
