### ISSUE TITLE
CPU spins at 100% for a good while after processing files completes

### ISSUE THREAD

**Issue by rodu** [leetreveil/musicmetadata#115]
I am writing a Chrome App and I am using the musicmetadata to run in the Chrome browser (Version 50.0.2661.86 (64-bit)).

Once I got the extraction of metadata well tuned, crawling some nested directories, I observed the CPU cores going up to 100% and staying so for a very long time depending on the number of files processed (as little as around 33 files).

Investigated this issue, I found that the FileReader used internally (filereader-stream package) keeps going after the `callback` function of `musicmetadata` has been called to pass back the results. I don't think there is any problem with filereader-stream, just it's reading the entire file content and this takes time.

I will submit a change for consideration, where the `abort` method on the `filestream-reader` is called once the `musicmetadata callback` has been called. Doing this fixed the issue for me, making the overall process more efficient.

In the mean time, I was unable to run the tests given a missing npm package `ansi-codes`.

**Comment by IrosTheBeggar** [comment]
Thanks for fixing this.  I was wondering why my code was slowing to a crawl when processing a few hundred files

**Comment by darkyen** [comment]
Don't know if this is related but this killed my Nexus5 with just 100 files, It was extremely fast for first 10 files but then it got incrementally slow. **Exponentially**
```bash
  PID PR CPU% S  #THR     VSS     RSS PCY UID      Name
21889  2  48% S    43 1338068K 242084K  fg u0_a84   org.clientname.project
```

Here is the ouput from `top`

**Comment by darkyen** [comment]
Also I'd like to mention that I am forcing it to only parse 3 files at the same time, so the insane memory usage is because of the lib.

**Comment by rodu** [comment]
You need to pass the flag `autoClose: true` to the `musicmetadata()` call options (as part of second argument) in order to use what was done in this fix. Without the flag the library works as before.

**Comment by darkyen** [comment]
@rodu I am doing that :-S

**Comment by rodu** [comment]
@darkyen the issue you are describing seems to be related to something different. You should be able to add or remove the `autoClose` flag and see if there are differences in using or not using it. If there are no differences, and your problem persists, then it must be related to something else. In that case you should probably open a specific issue for that. Thanks for your testing.

**Comment by darkyen** [comment]
I ended up using an ID3 decoder I wrote 3 years back :P Idk what but I will dig into this.

**Comment by IrosTheBeggar** [comment]
@darkyen 
I noticed these changes haven't ben put into a release yet.  The last release on npm was published 7 months ago.  Maybe you're using an older version?

**Comment by darkyen** [comment]
</3

**Comment by leetreveil** [comment]
I've updated the documentation to explain how to close the stream yourself:

```js
var readableStream = fs.createReadStream('sample.mp3');
var parser = mm(readableStream, function (err, metadata) {
  if (err) throw err;
  readableStream.close();
});
```
