### ISSUE TITLE
No '.dest' field on node streams.

### ISSUE THREAD

**Issue by Skeen** [leetreveil/musicmetadata#120]
The pull request; "Aborts stream file reader once metadata are returned" (#116) changed;
```
return musicmetadata(wrapFileWithStream(stream), opts, callback)
```
in essence to;
```
return musicmetadata(wrapFileWithStream(stream).dest, opts, callback)
```
My node [Readable Stream](https://nodejs.org/api/stream.html#stream_class_stream_readable), does NOT have such a field, and thus my code is broken by this change.

Additionally I do not believe it to be the general interface of node streams to have `.dest` fields.

**Comment by leetreveil** [comment]
K i'll revert the change and push a `2.0.4` since it's an api breaking change.

**Comment by leetreveil** [comment]
Pushed 2.0.4 @ https://github.com/leetreveil/musicmetadata/commit/9209b4f52b6a5cf40a1fdafc104ab5d0e2b9db7d

**Comment by Skeen** [comment]
I'd like to express that I do like the idea introduced in #116, if it could be achieved in a non-breaking way :)
