### ISSUE TITLE
window is not defined, when running from nodejs

### ISSUE THREAD

**Issue by ajmas** [leetreveil/musicmetadata#121]
I am getting a 'window is not defined', at line musicmetadata/dist/musicmetadata.js:270, when running from nodejs. The current code here is:

```
  if (file instanceof window.ArrayBuffer) {
    return wrapArrayBufferWithStream(file, stream)
  }

```

Proposed minimum change is:

```
  if (typeof window !== 'undefined' && file instanceof window.ArrayBuffer) {
    return wrapArrayBufferWithStream(file, stream)
  }
```

At the same time the whole `wrapFileWithStream()` method should be changed to work when not in a web browser. For example, the following additional changes:

```
  if (typeof window !== 'undefined' && file instanceof window.FileList) {
    throw new Error('You have passed a FileList object but we expected a File')
  }
  if (typeof window !== 'undefined' && !(file instanceof window.File || file instanceof window.Blob)) {
    throw new Error('You must provide a valid File or Blob object')
  }
```

**Comment by leetreveil** [comment]
`dist/musicmetadata.js` is indented to be used from a browser based environment.

Do `npm install musicmetadata` and use `var mm = require('musicmetadata')` for nodejs.
