### ISSUE TITLE
'Could not find metadata header' with some mp3s 

### ISSUE THREAD

**Issue by bhj** [leetreveil/musicmetadata#126]
Getting this error on a number of files, and while not really concerned about the missing header (the metadata would likely be blank anyway) would still like the duration. 

[mp3-duration](https://github.com/ddsol/mp3-duration) does work fine on these. Any chance of implementing a similar strategy? Would also solve #60 I believe.

**Comment by leetreveil** [comment]
Do you have a sample file?

**Comment by bhj** [comment]
Emailed! Thanks for taking a look.

**Comment by bhj** [comment]
@leetreveil Just seeing if you had any luck with that. Thanks for your help.

**Comment by leetreveil** [comment]
I looked into this. The sample file you emailed me does not have a ID3 header.

Unfortunately, `musicmetadata` uses this header information to detect which parser to use.

It's never going to be able to parse these files while automatically detecting the metadata format.

Sorry about that!

**Comment by bhj** [comment]
@leetreveil Makes sense, though not all mp3s have ID3s, and it'd be nice even if duration were all it could report. Consider it a FR :) Thanks for the response.
