### ISSUE TITLE
No metadata in file that has metadata

### ISSUE THREAD

**Issue by DracotMolver** [leetreveil/musicmetadata#127]
Hi.
I have a file that has some metadata (I know it because I was using ffmpeg months ago to get metadata) but when I try to read this file I get this:

```
Error: expected frame header but was not found at seekFirstAudioFrame 
```

I'm using mp3 files.

**Comment by leetreveil** [comment]
Can you send me the mp3 file?

**Comment by leetreveil** [comment]
Did you send me the file for this? I cannot remember.
