### ISSUE TITLE
Webpack, fs and HTML 5 File object

### ISSUE THREAD

**Issue by a-koka** [leetreveil/musicmetadata#128]
I'm having trouble using this with `Webpack` as it doesn't support the use of `fs`. My goal is to use a `File` object sourced from an `<input type="file" />` element. Is there a way to make this work with just a `File` object?

Thank you!

**Comment by leetreveil** [comment]
Yeah there's a heavy dependency on node modules which have to be built with browserfy.

You might want to try the pre packaged version:

https://github.com/leetreveil/musicmetadata/blob/master/dist/musicmetadata.js
