### ISSUE TITLE
error when extract image

### ISSUE THREAD

**Issue by jbelda** [leetreveil/musicmetadata#131]
Sometimes when the image is large than 45 kb i can't save the image completely
![lvlup](https://cloud.githubusercontent.com/assets/11690517/19335210/89f5d6ac-90cf-11e6-9d8d-c0196b1c1ffb.jpg)

**Comment by leetreveil** [comment]
Can you send me the audio file?

**Comment by leetreveil** [comment]
Did you send me the file for this? I cannot remember. Feel free to re-open.

**Comment by jbelda** [comment]
hi!!! sorry... my fault!!!! i declare a blob in a  mysql table but max. size for this blob is 45 kb. I change the size of the blob and everything works great!!!!!
