### ISSUE TITLE
Include file bitrate in the metadata

### ISSUE THREAD

**Issue by MichaelZer0** [leetreveil/musicmetadata#43]
Looking at [test/test-id3-bitrate-calculator.js](https://github.com/leetreveil/musicmetadata/blob/master/test/test-id3-bitrate-calculator.js) you're apparently already doing something with it, but it'd be nice to have it exposed in the public API.

**Comment by Borewit** [comment]
Working on it: https://github.com/Borewit/musicmetadata/tree/encoding_info
