### ISSUE TITLE
Adding a way to determine that a file has no metadata

### ISSUE THREAD

**Issue by Hydrothermal** [leetreveil/musicmetadata#76]
This bit of code ([lib/index.js:106](https://github.com/leetreveil/musicmetadata/blob/master/lib/index.js#L106), added in 067e96e2701e01d340dcd0edc2d3c5c2dd808777) avoids emitting the `metadata` event if a file has no metadata.

    if (Object.keys(aliased).length > 0) {
      emitter.emit('metadata', metadata);
    }

I understand the logic behind it, but as far as I can tell, it leaves no way to handle trying to parse files that have no metadata. It'd be nice if there was some way to implement this - possibilities include firing an empty `metadata` event, adding a new event for no metadata, or firing the `done` event with a descriptive error. Any of these three would be fairly trivial changes. Thoughts?

**Comment by leetreveil** [comment]
One unsatisfying workaround is to set a flag when the `metadata` event is raised, to be checked in the `end` event.

The other way is to rewrite the api to follow the (err, result) model:

```javascript
musicmetadata(filestream, function (err, metadata) {
    if (err) throw err;
    if (!metadata) {
        throw new Error('no metadata!')
    }
}
```
I MUCH prefer this style of writing node modules now vs the `EventEmitter` model, however making a change like this would break backward compatibility for everyone.

**Comment by leetreveil** [comment]
This has actually been implemented.
