### ISSUE TITLE
additional info

### ISSUE THREAD

**Issue by nickdesaulniers** [leetreveil/musicmetadata#81]
Hey buddy, one of my coworkers who wrote an mp3 decoder sent me [this](http://mpgedit.org/mpgedit/mpeg_format/mpeghdr.htm).  I figure you're probably past that point, but you never know.  Anyways, when he sent me this I thought of you.  Hopefully it helps!

**Comment by leetreveil** [comment]
Haha I have read that document many times :) I really appreciate the thought though!
