### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'opts.hasOwnProperty')

### ISSUE THREAD

**Issue by BeamerCola** [leetreveil/musicmetadata#87]
getting this in all browsers with example code

**Comment by leetreveil** [comment]
Fixed in https://github.com/leetreveil/musicmetadata/commit/af03c2e07f88c3d7c96ae37c1e8ad1b97587eb23

**Comment by floydpink** [comment]
@leetreveil Could you please publish this patch to npm as well?

And, thank you very much for the module!

**Comment by leetreveil** [comment]
Done.
